apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-a-staging

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/madriam/admin-panel
    newTag: latest
