apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: admin-panel
resources:
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/madriam/super-admin-panel
    newTag: latest
